/* Compiles the markdown in content/ into the typed data modules the app reads:
 *   npm run content
 * The generated files under src/data are committed, so a normal build needs
 * nothing but this repository — the markdown is the thing you edit, and this
 * script is what turns it into something the app can import.
 *
 * The parser handles the subset of YAML the content files actually use:
 * scalars, inline arrays, one level of nested maps, and a list of image
 * objects. See CONTENT.md for what each field means. */
import fs from 'node:fs';
import path from 'node:path';

const SRC = process.argv[2] ?? 'content';
const OUT = path.resolve('src/data');

const scalar = (raw) => {
  const v = raw.trim();
  if (v === '') return null;
  if (v === 'true') return true;
  if (v === 'false') return false;
  if (v === 'null') return null;
  if (/^\[.*\]$/.test(v)) return JSON.parse(v.replace(/'/g, '"'));
  if (/^-?\d+(\.\d+)?$/.test(v)) return Number(v);
  if (/^".*"$/.test(v) || /^'.*'$/.test(v)) return v.slice(1, -1);
  return v;
};

/** Splits `key: value`, honouring a quoted key such as `"Doors and windows":`. */
const splitPair = (line) => {
  const m = line.match(/^("(?:[^"]*)"|[^:]+):\s?(.*)$/);
  if (!m) return null;
  return [m[1].replace(/^"|"$/g, ''), m[2]];
};

function parseFrontmatter(text) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) throw new Error('no frontmatter');
  const [, head, body] = m;
  const data = {};
  const lines = head.split(/\r?\n/);

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.trim() || line.startsWith('#')) continue;
    if (/^\s/.test(line)) continue; // consumed by a block below
    const pair = splitPair(line);
    if (!pair) continue;
    const [key, rest] = pair;

    if (rest.trim() !== '') { data[key] = scalar(rest); continue; }

    // Block value: either a list of maps (images) or a nested map (specifications).
    const block = [];
    while (i + 1 < lines.length && (/^\s+\S/.test(lines[i + 1]) || lines[i + 1].trim() === '')) {
      block.push(lines[++i]);
    }
    const items = [];
    let current = null;
    let map = null;
    for (const b of block) {
      if (!b.trim()) continue;
      const listItem = b.match(/^\s*-\s+(.*)$/);
      if (listItem) {
        current = {};
        items.push(current);
        const p = splitPair(listItem[1]);
        if (p) current[p[0]] = scalar(p[1]);
        continue;
      }
      const p = splitPair(b.trim());
      if (!p) continue;
      if (current) current[p[0]] = scalar(p[1]);
      else { map ??= {}; map[p[0]] = scalar(p[1]); }
    }
    data[key] = items.length ? items : (map ?? []);
  }
  return { data, body: body.trim() };
}

const read = (dir) =>
  fs.readdirSync(path.join(SRC, dir))
    .filter((f) => f.endsWith('.md'))
    .map((f) => {
      const { data, body } = parseFrontmatter(
        fs.readFileSync(path.join(SRC, dir, f), 'utf8'),
      );
      return { id: f.replace(/\.md$/, ''), ...data, body };
    });

const projects = read('projects').map((p) => ({
  id: p.id,
  name: p.name,
  locality: p.locality,
  status: p.status,
  reraNumber: p.reraNumber ?? null,
  reraVerified: p.reraVerified ?? false,
  yearCompleted: p.yearCompleted ?? null,
  possessionDate: p.possessionDate ?? null,
  unitTypes: p.unitTypes ?? [],
  carpetAreaMin: p.carpetAreaMin ?? null,
  carpetAreaMax: p.carpetAreaMax ?? null,
  totalUnits: p.totalUnits ?? null,
  unitsAvailable: p.unitsAvailable ?? null,
  floors: p.floors ?? null,
  address: p.address ?? null,
  lat: p.lat ?? null,
  lng: p.lng ?? null,
  specifications: Array.isArray(p.specifications) ? null : (p.specifications ?? null),
  amenities: p.amenities ?? [],
  nearby: p.nearby ?? null,
  images: (Array.isArray(p.images) ? p.images : []).map((i) => ({
    src: i.src, alt: i.alt, standIn: i.standIn ?? false,
  })),
  featured: p.featured ?? false,
  summary: p.summary ?? '',
  copyIsDraft: p.copyIsDraft ?? true,
  body: p.body.split(/\n\s*\n/).map((s) => s.replace(/\s*\n\s*/g, ' ').trim()).filter(Boolean),
}));

const institutional = read('institutional')
  .map(({ id, organisation, scope, year, status, order, copyIsDraft }) =>
    ({ id, organisation, scope, year, status, order: order ?? 0, copyIsDraft: copyIsDraft ?? true }))
  .sort((a, b) => a.order - b.order);

const credits = JSON.parse(fs.readFileSync(path.join(SRC, 'image-credits.json'), 'utf8'));

const banner = `/* GENERATED by scripts/gen-content.mjs from the markdown content\n * collections. Edit the markdown and re-run the script; do not edit here. */\n\n`;

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(
  path.join(OUT, 'projects.ts'),
  banner +
    `import type { Project } from '@/lib/types';\n\n` +
    `export const projects: Project[] = ${JSON.stringify(projects, null, 2)};\n`,
);
fs.writeFileSync(
  path.join(OUT, 'institutional.ts'),
  banner +
    `import type { InstitutionalClient } from '@/lib/types';\n\n` +
    `export const institutional: InstitutionalClient[] = ${JSON.stringify(institutional, null, 2)};\n`,
);
fs.writeFileSync(
  path.join(OUT, 'image-credits.ts'),
  banner +
    `import type { ImageCredit } from '@/lib/types';\n\n` +
    `export const imageCredits: ImageCredit[] = ${JSON.stringify(credits, null, 2)};\n`,
);

console.log(`projects: ${projects.length}  institutional: ${institutional.length}  credits: ${credits.length}`);
const live = projects.filter((p) => p.status === 'available' || p.status === 'under-construction');
console.log(`live: ${live.map((p) => `${p.name} [${p.reraNumber}]`).join(', ')}`);
