/* GENERATED by scripts/gen-content.mjs from the markdown content
 * collections. Edit the markdown and re-run the script; do not edit here. */

import type { InstitutionalClient } from '@/lib/types';

export const institutional: InstitutionalClient[] = [
  {
    "id": "balmer-lawrie",
    "organisation": "Balmer Lawrie & Co. Ltd",
    "scope": "Civil works and building maintenance under contract",
    "year": "—",
    "status": "Completed",
    "order": 1,
    "copyIsDraft": true
  },
  {
    "id": "bicco-lawrie",
    "organisation": "Bicco Lawrie Ltd",
    "scope": "Civil and structural works under contract",
    "year": "—",
    "status": "Completed",
    "order": 2,
    "copyIsDraft": true
  },
  {
    "id": "lt-subcontract",
    "organisation": "Larsen & Toubro",
    "scope": "Engaged as subcontractor on civil packages",
    "year": "—",
    "status": "Completed",
    "order": 3,
    "copyIsDraft": true
  }
];
