/* GENERATED by scripts/gen-content.mjs from the markdown content
 * collections. Edit the markdown and re-run the script; do not edit here. */

import type { Project } from '@/lib/types';

export const projects: Project[] = [
  {
    "id": "barnali-apartments",
    "name": "Barnali Apartments",
    "locality": "Garfa",
    "status": "under-construction",
    "reraNumber": "WBRERA/P/SOU/2025/XXXXXX",
    "reraVerified": false,
    "yearCompleted": null,
    "possessionDate": "March 2027",
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": 720,
    "carpetAreaMax": 1040,
    "totalUnits": 10,
    "unitsAvailable": 7,
    "floors": 4,
    "address": "Garfa, Kolkata, West Bengal 700075",
    "lat": 22.4977,
    "lng": 88.3821,
    "specifications": {
      "Structure": "RCC framed structure, seismic zone III.",
      "Flooring": "Vitrified tiles throughout, anti-skid ceramic in bathrooms and balconies.",
      "Kitchen": "Granite counter with stainless steel sink and glazed tile dado.",
      "Bathrooms": "Concealed plumbing with CP fittings.",
      "Electrical": "Concealed copper wiring, modular switches, MCB board.",
      "Doors and windows": "Hardwood frames with flush shutters; aluminium sliding windows.",
      "Lift": "Passenger lift with automatic rescue device.",
      "Water": "Underground reservoir and overhead tank with deep tubewell reserve.",
      "Parking": "Covered parking at ground level."
    },
    "amenities": [
      "Lift",
      "Covered parking",
      "Intercom",
      "Standby generator for common areas"
    ],
    "nearby": "Garfa Main Road and the Jadavpur railway station are both within walking distance. Santoshpur Avenue market is a kilometre north. Jadavpur University is two kilometres away.",
    "images": [
      {
        "src": "/images/projects/barnali-a.jpg",
        "alt": "Reinforced concrete slab under construction, with timber formwork and steel reinforcement in place. Stand-in photograph.",
        "standIn": true
      },
      {
        "src": "/images/projects/barnali-b.jpg",
        "alt": "Concrete frame of a residential building under construction, cast to roof level. Stand-in photograph.",
        "standIn": true
      }
    ],
    "featured": true,
    "summary": "Ten flats in Garfa. Casting is at third-floor level. Possession March 2027.",
    "copyIsDraft": true,
    "body": [
      "Ten flats on a Garfa plot where an old single-storey house stood until last year. Casting is at third-floor level. Brickwork on the lower floors has started.",
      "Buying at this stage means you can still watch how the building is being put together, which is really the argument for doing it. Ask to be shown the reinforcement before the next slab goes in."
    ]
  },
  {
    "id": "prarthana",
    "name": "Prarthana",
    "locality": "Santoshpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 1995,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 8,
    "unitsAvailable": null,
    "floors": 3,
    "address": "Santoshpur, Kolkata",
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/prarthana-a.jpg",
        "alt": "Three-storey residential building with balconies on a tree-lined Santoshpur street. Stand-in photograph.",
        "standIn": true
      }
    ],
    "featured": true,
    "summary": "The first building. Eight flats in Santoshpur, handed over in 1995.",
    "copyIsDraft": false,
    "body": [
      "The first building Ashima Engineering finished. It went up on a Santoshpur plot belonging to a family who decided to develop rather than sell, and it is named after the founder's daughter.",
      "Eight flats over three floors. It set the pattern for everything that came after, joint-venture terms, a small building, and the owner's share written down before anything was signed."
    ]
  },
  {
    "id": "sample-alaknanda",
    "name": "Alaknanda",
    "locality": "Sonarpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2001,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 24,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-e.jpg",
        "alt": "Street elevation of a mid-rise residential building with shopfronts at ground level. Stand-in photograph for Alaknanda in Sonarpur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "24 flats in Sonarpur, handed over in 2001.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Alaknanda is standing in for one of the buildings Ashima Engineering has finished in Sonarpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-amrapali",
    "name": "Amrapali",
    "locality": "Sonarpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2011,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 16,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "16 flats in Sonarpur, handed over in 2011.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Amrapali is standing in for one of the buildings Ashima Engineering has finished in Sonarpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-anandalok",
    "name": "Anandalok",
    "locality": "Haltu",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 1997,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 24,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "24 flats in Haltu, handed over in 1997.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Anandalok is standing in for one of the buildings Ashima Engineering has finished in Haltu. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-antara",
    "name": "Antara",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2017,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 10,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "10 flats in Mukundapur, handed over in 2017.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Antara is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-anwesha",
    "name": "Anwesha",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2007,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 13,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-f.jpg",
        "alt": "Blue-painted low-rise building at a road junction with a boundary wall. Stand-in photograph for Anwesha in Garfa.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "13 flats in Garfa, handed over in 2007.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Anwesha is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-aparajita",
    "name": "Aparajita",
    "locality": "Haltu",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2000,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 24,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-c.jpg",
        "alt": "Residential building with plant-filled balconies on a narrow South Kolkata lane. Stand-in photograph for Aparajita in Haltu.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "24 flats in Haltu, handed over in 2000.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Aparajita is standing in for one of the buildings Ashima Engineering has finished in Haltu. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-ashalata",
    "name": "Ashalata",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2016,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 22,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "22 flats in Garfa, handed over in 2016.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Ashalata is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-ashiyana",
    "name": "Ashiyana",
    "locality": "Kasba",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 1996,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 9,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "9 flats in Kasba, handed over in 1996.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Ashiyana is standing in for one of the buildings Ashima Engineering has finished in Kasba. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-bakul",
    "name": "Bakul",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2012,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 18,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "18 flats in Mukundapur, handed over in 2012.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Bakul is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-barnali",
    "name": "Barnali",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2005,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 23,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "23 flats in Mukundapur, handed over in 2005.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Barnali is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-basundhara",
    "name": "Basundhara",
    "locality": "Haltu",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 1998,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 13,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "13 flats in Haltu, handed over in 1998.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Basundhara is standing in for one of the buildings Ashima Engineering has finished in Haltu. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-bhaswati",
    "name": "Bhaswati",
    "locality": "Santoshpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2015,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 17,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-f.jpg",
        "alt": "Blue-painted low-rise building at a road junction with a boundary wall. Stand-in photograph for Bhaswati in Santoshpur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "17 flats in Santoshpur, handed over in 2015.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Bhaswati is standing in for one of the buildings Ashima Engineering has finished in Santoshpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-bhramari",
    "name": "Bhramari",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2020,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 11,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "11 flats in Garfa, handed over in 2020.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Bhramari is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-bithika",
    "name": "Bithika",
    "locality": "Haltu",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2008,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 21,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "21 flats in Haltu, handed over in 2008.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Bithika is standing in for one of the buildings Ashima Engineering has finished in Haltu. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-chandrima",
    "name": "Chandrima",
    "locality": "Jadavpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 1999,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 9,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "9 flats in Jadavpur, handed over in 1999.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Chandrima is standing in for one of the buildings Ashima Engineering has finished in Jadavpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-charulata",
    "name": "Charulata",
    "locality": "Baruipur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2008,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 14,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-c.jpg",
        "alt": "Residential building with plant-filled balconies on a narrow South Kolkata lane. Stand-in photograph for Charulata in Baruipur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "14 flats in Baruipur, handed over in 2008.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Charulata is standing in for one of the buildings Ashima Engineering has finished in Baruipur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-chitralekha",
    "name": "Chitralekha",
    "locality": "Santoshpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2020,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 16,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "16 flats in Santoshpur, handed over in 2020.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Chitralekha is standing in for one of the buildings Ashima Engineering has finished in Santoshpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-debalaya",
    "name": "Debalaya",
    "locality": "Santoshpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2002,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 18,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "18 flats in Santoshpur, handed over in 2002.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Debalaya is standing in for one of the buildings Ashima Engineering has finished in Santoshpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-devjani",
    "name": "Devjani",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2021,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 24,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "24 flats in Garfa, handed over in 2021.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Devjani is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-dipanwita",
    "name": "Dipanwita",
    "locality": "Jadavpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2006,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 16,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "16 flats in Jadavpur, handed over in 2006.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Dipanwita is standing in for one of the buildings Ashima Engineering has finished in Jadavpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-hemanti",
    "name": "Hemanti",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2022,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 9,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "9 flats in Garfa, handed over in 2022.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Hemanti is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-ipsita",
    "name": "Ipsita",
    "locality": "Jadavpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2017,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 15,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-f.jpg",
        "alt": "Blue-painted low-rise building at a road junction with a boundary wall. Stand-in photograph for Ipsita in Jadavpur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "15 flats in Jadavpur, handed over in 2017.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Ipsita is standing in for one of the buildings Ashima Engineering has finished in Jadavpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-jayanti",
    "name": "Jayanti",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2017,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 16,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-a.jpg",
        "alt": "Four-storey residential block with projecting balconies and a mature tree at the kerb. Stand-in photograph for Jayanti in Mukundapur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "16 flats in Mukundapur, handed over in 2017.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Jayanti is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-jharna",
    "name": "Jharna",
    "locality": "Sonarpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2011,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 10,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-d.jpg",
        "alt": "Low-rise apartment building set back behind trees on a quiet residential street. Stand-in photograph for Jharna in Sonarpur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "10 flats in Sonarpur, handed over in 2011.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Jharna is standing in for one of the buildings Ashima Engineering has finished in Sonarpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-kaberi",
    "name": "Kaberi",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2016,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 19,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-b.jpg",
        "alt": "Cream and pink apartment blocks seen from the road, with parked cars below. Stand-in photograph for Kaberi in Garfa.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "19 flats in Garfa, handed over in 2016.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Kaberi is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-krishnakoli",
    "name": "Krishnakoli",
    "locality": "Haltu",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2010,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 14,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "14 flats in Haltu, handed over in 2010.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Krishnakoli is standing in for one of the buildings Ashima Engineering has finished in Haltu. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-kusumika",
    "name": "Kusumika",
    "locality": "Haltu",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2003,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 10,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-e.jpg",
        "alt": "Street elevation of a mid-rise residential building with shopfronts at ground level. Stand-in photograph for Kusumika in Haltu.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "10 flats in Haltu, handed over in 2003.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Kusumika is standing in for one of the buildings Ashima Engineering has finished in Haltu. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-madhabi",
    "name": "Madhabi",
    "locality": "Baruipur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 1999,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 10,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "10 flats in Baruipur, handed over in 1999.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Madhabi is standing in for one of the buildings Ashima Engineering has finished in Baruipur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-maitreyi",
    "name": "Maitreyi",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2015,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 13,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-a.jpg",
        "alt": "Four-storey residential block with projecting balconies and a mature tree at the kerb. Stand-in photograph for Maitreyi in Garfa.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "13 flats in Garfa, handed over in 2015.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Maitreyi is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-malabika",
    "name": "Malabika",
    "locality": "Sonarpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2021,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 6,
    "unitsAvailable": null,
    "floors": 3,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "6 flats in Sonarpur, handed over in 2021.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Malabika is standing in for one of the buildings Ashima Engineering has finished in Sonarpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-meghmallar",
    "name": "Meghmallar",
    "locality": "Santoshpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2004,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 8,
    "unitsAvailable": null,
    "floors": 3,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "8 flats in Santoshpur, handed over in 2004.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Meghmallar is standing in for one of the buildings Ashima Engineering has finished in Santoshpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-mrinalini",
    "name": "Mrinalini",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2007,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 22,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-a.jpg",
        "alt": "Four-storey residential block with projecting balconies and a mature tree at the kerb. Stand-in photograph for Mrinalini in Garfa.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "22 flats in Garfa, handed over in 2007.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Mrinalini is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-nabaneeta",
    "name": "Nabaneeta",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2018,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 23,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "23 flats in Mukundapur, handed over in 2018.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Nabaneeta is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-nandini",
    "name": "Nandini",
    "locality": "Sonarpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2010,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 14,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "14 flats in Sonarpur, handed over in 2010.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Nandini is standing in for one of the buildings Ashima Engineering has finished in Sonarpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-neelkantha",
    "name": "Neelkantha",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2013,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 18,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "18 flats in Mukundapur, handed over in 2013.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Neelkantha is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-nilanjana",
    "name": "Nilanjana",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 1998,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 12,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "12 flats in Mukundapur, handed over in 1998.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Nilanjana is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-oindrila",
    "name": "Oindrila",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2018,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 18,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "18 flats in Mukundapur, handed over in 2018.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Oindrila is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-padmini",
    "name": "Padmini",
    "locality": "Jadavpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2013,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 17,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-c.jpg",
        "alt": "Residential building with plant-filled balconies on a narrow South Kolkata lane. Stand-in photograph for Padmini in Jadavpur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "17 flats in Jadavpur, handed over in 2013.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Padmini is standing in for one of the buildings Ashima Engineering has finished in Jadavpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-piyali",
    "name": "Piyali",
    "locality": "Haltu",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2019,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 14,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-d.jpg",
        "alt": "Low-rise apartment building set back behind trees on a quiet residential street. Stand-in photograph for Piyali in Haltu.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "14 flats in Haltu, handed over in 2019.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Piyali is standing in for one of the buildings Ashima Engineering has finished in Haltu. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-priyadarshini",
    "name": "Priyadarshini",
    "locality": "Santoshpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2003,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 19,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "19 flats in Santoshpur, handed over in 2003.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Priyadarshini is standing in for one of the buildings Ashima Engineering has finished in Santoshpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-purnima",
    "name": "Purnima",
    "locality": "Jadavpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2009,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 21,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-e.jpg",
        "alt": "Street elevation of a mid-rise residential building with shopfronts at ground level. Stand-in photograph for Purnima in Jadavpur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "21 flats in Jadavpur, handed over in 2009.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Purnima is standing in for one of the buildings Ashima Engineering has finished in Jadavpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-rangana",
    "name": "Rangana",
    "locality": "Jadavpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2003,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 13,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "13 flats in Jadavpur, handed over in 2003.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Rangana is standing in for one of the buildings Ashima Engineering has finished in Jadavpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-rituparna",
    "name": "Rituparna",
    "locality": "Sonarpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2019,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 14,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-e.jpg",
        "alt": "Street elevation of a mid-rise residential building with shopfronts at ground level. Stand-in photograph for Rituparna in Sonarpur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "14 flats in Sonarpur, handed over in 2019.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Rituparna is standing in for one of the buildings Ashima Engineering has finished in Sonarpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-ritwika",
    "name": "Ritwika",
    "locality": "Santoshpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2004,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 18,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-a.jpg",
        "alt": "Four-storey residential block with projecting balconies and a mature tree at the kerb. Stand-in photograph for Ritwika in Santoshpur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "18 flats in Santoshpur, handed over in 2004.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Ritwika is standing in for one of the buildings Ashima Engineering has finished in Santoshpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-rupkatha",
    "name": "Rupkatha",
    "locality": "Santoshpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2011,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 13,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "13 flats in Santoshpur, handed over in 2011.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Rupkatha is standing in for one of the buildings Ashima Engineering has finished in Santoshpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-sanchita",
    "name": "Sanchita",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2022,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 22,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-f.jpg",
        "alt": "Blue-painted low-rise building at a road junction with a boundary wall. Stand-in photograph for Sanchita in Garfa.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "22 flats in Garfa, handed over in 2022.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Sanchita is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-sharbari",
    "name": "Sharbari",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2014,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 18,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "18 flats in Garfa, handed over in 2014.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Sharbari is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-shatarupa",
    "name": "Shatarupa",
    "locality": "Haltu",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2016,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 24,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "24 flats in Haltu, handed over in 2016.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Shatarupa is standing in for one of the buildings Ashima Engineering has finished in Haltu. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-shree-niketan",
    "name": "Shree Niketan",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 1996,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 18,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-b.jpg",
        "alt": "Cream and pink apartment blocks seen from the road, with parked cars below. Stand-in photograph for Shree Niketan in Garfa.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "18 flats in Garfa, handed over in 1996.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Shree Niketan is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-shreyashi",
    "name": "Shreyashi",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2006,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 24,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "24 flats in Mukundapur, handed over in 2006.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Shreyashi is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-shyamali",
    "name": "Shyamali",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2012,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 11,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-f.jpg",
        "alt": "Blue-painted low-rise building at a road junction with a boundary wall. Stand-in photograph for Shyamali in Mukundapur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "11 flats in Mukundapur, handed over in 2012.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Shyamali is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-sohini",
    "name": "Sohini",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2019,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 13,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-f.jpg",
        "alt": "Blue-painted low-rise building at a road junction with a boundary wall. Stand-in photograph for Sohini in Garfa.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "13 flats in Garfa, handed over in 2019.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Sohini is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-sonali",
    "name": "Sonali",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2002,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 10,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "10 flats in Mukundapur, handed over in 2002.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Sonali is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-sraboni",
    "name": "Sraboni",
    "locality": "Jadavpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 1997,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 14,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-d.jpg",
        "alt": "Low-rise apartment building set back behind trees on a quiet residential street. Stand-in photograph for Sraboni in Jadavpur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "14 flats in Jadavpur, handed over in 1997.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Sraboni is standing in for one of the buildings Ashima Engineering has finished in Jadavpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-sudeshna",
    "name": "Sudeshna",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2009,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 22,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-f.jpg",
        "alt": "Blue-painted low-rise building at a road junction with a boundary wall. Stand-in photograph for Sudeshna in Mukundapur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "22 flats in Mukundapur, handed over in 2009.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Sudeshna is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-suravi",
    "name": "Suravi",
    "locality": "Garfa",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2005,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 20,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "20 flats in Garfa, handed over in 2005.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Suravi is standing in for one of the buildings Ashima Engineering has finished in Garfa. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-tanushree",
    "name": "Tanushree",
    "locality": "Jadavpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2008,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 6,
    "unitsAvailable": null,
    "floors": 3,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "6 flats in Jadavpur, handed over in 2008.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Tanushree is standing in for one of the buildings Ashima Engineering has finished in Jadavpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-tapati",
    "name": "Tapati",
    "locality": "Mukundapur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2022,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 19,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [
      {
        "src": "/images/projects/record-a.jpg",
        "alt": "Four-storey residential block with projecting balconies and a mature tree at the kerb. Stand-in photograph for Tapati in Mukundapur.",
        "standIn": true
      }
    ],
    "featured": false,
    "summary": "19 flats in Mukundapur, handed over in 2022.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Tapati is standing in for one of the buildings Ashima Engineering has finished in Mukundapur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-trinayani",
    "name": "Trinayani",
    "locality": "Sonarpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2000,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 11,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "11 flats in Sonarpur, handed over in 2000.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Trinayani is standing in for one of the buildings Ashima Engineering has finished in Sonarpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-urmila",
    "name": "Urmila",
    "locality": "Santoshpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2020,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 7,
    "unitsAvailable": null,
    "floors": 3,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "7 flats in Santoshpur, handed over in 2020.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Urmila is standing in for one of the buildings Ashima Engineering has finished in Santoshpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-ushashi",
    "name": "Ushashi",
    "locality": "Jadavpur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2001,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 11,
    "unitsAvailable": null,
    "floors": 4,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "11 flats in Jadavpur, handed over in 2001.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Ushashi is standing in for one of the buildings Ashima Engineering has finished in Jadavpur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sample-utsarga",
    "name": "Utsarga",
    "locality": "Baruipur",
    "status": "completed",
    "reraNumber": null,
    "reraVerified": false,
    "yearCompleted": 2014,
    "possessionDate": null,
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": null,
    "carpetAreaMax": null,
    "totalUnits": 15,
    "unitsAvailable": null,
    "floors": 5,
    "address": null,
    "lat": null,
    "lng": null,
    "specifications": null,
    "amenities": [],
    "nearby": null,
    "images": [],
    "featured": false,
    "summary": "15 flats in Baruipur, handed over in 2014.",
    "copyIsDraft": true,
    "body": [
      "Sample entry, generated so the record page could be laid out and reviewed. Replace the details above with the real figures for this project, or delete the file. Utsarga is standing in for one of the buildings Ashima Engineering has finished in Baruipur. The name, the year and the number of flats are all invented."
    ]
  },
  {
    "id": "sraboni-court",
    "name": "Sraboni Court",
    "locality": "Mukundapur",
    "status": "available",
    "reraNumber": "WBRERA/P/SOU/2024/XXXXXX",
    "reraVerified": false,
    "yearCompleted": null,
    "possessionDate": "December 2026",
    "unitTypes": [
      "2 BHK",
      "3 BHK"
    ],
    "carpetAreaMin": 685,
    "carpetAreaMax": 1120,
    "totalUnits": 14,
    "unitsAvailable": 5,
    "floors": 4,
    "address": "Mukundapur, Kolkata, West Bengal 700099",
    "lat": 22.5031,
    "lng": 88.3985,
    "specifications": {
      "Structure": "RCC framed structure on a raft foundation, designed to IS 1893 seismic zone III.",
      "Flooring": "Vitrified tiles in living, dining and bedrooms. Anti-skid ceramic tiles in bathrooms and balconies.",
      "Kitchen": "Granite counter, stainless steel sink, glazed tile dado to two feet above counter, provision for exhaust and water purifier.",
      "Bathrooms": "Concealed plumbing, CP fittings, provision for geyser in the master bathroom.",
      "Electrical": "Concealed copper wiring with modular switches, MCB distribution board, AC point in each bedroom.",
      "Doors and windows": "Seasoned hardwood frames, flush doors with laminate finish. Aluminium sliding windows with mosquito mesh provision.",
      "Lift": "Passenger lift with automatic rescue device.",
      "Water": "Underground reservoir and overhead tank, pump-fed, with a deep tubewell as reserve.",
      "Parking": "Covered parking at ground level, allotted."
    },
    "amenities": [
      "Lift",
      "Covered parking",
      "Standby generator for common areas",
      "Intercom",
      "Rainwater harvesting pit"
    ],
    "nearby": "Ruby General Hospital and the Eastern Metropolitan Bypass are within two kilometres. The Mukundapur bus stand is a five-minute walk. Local markets are on Mukundapur Main Road; the nearest schools are in Santoshpur and Kalikapur.",
    "images": [
      {
        "src": "/images/projects/sraboni-a.jpg",
        "alt": "Four-storey residential building with projecting balconies and a mature tree at the kerb. Stand-in photograph.",
        "standIn": true
      },
      {
        "src": "/images/projects/sraboni-b.jpg",
        "alt": "Cream and pink residential blocks seen from the approach road. Stand-in photograph.",
        "standIn": true
      },
      {
        "src": "/images/projects/sraboni-c.jpg",
        "alt": "Street elevation of a residential building with balconies above ground-floor shopfronts. Stand-in photograph.",
        "standIn": true
      }
    ],
    "featured": true,
    "summary": "Fourteen flats in Mukundapur. Two and three bedroom. Possession December 2026.",
    "copyIsDraft": true,
    "body": [
      "Fourteen flats over four floors on a plot off Mukundapur Main Road, developed on joint-venture terms with the family who have owned the land since the nineteen sixties. Two and three bedroom flats, five still unsold.",
      "It is the kind of four-storey building we have been putting up in these localities for thirty years. No podium and no clubhouse. Covered parking at ground level, and a lift that reaches every floor.",
      "Come and see the site before you decide. Somebody is there most mornings."
    ]
  }
];
